[workspace]
members = [
    "basics/account-data/anchor/programs/anchor-program-example",
    "basics/checking-accounts/anchor/programs/anchor-program-example",
    "basics/close-account/anchor/programs/close-account",
    "basics/counter/anchor/programs/counter_anchor",
    "basics/create-account/anchor/programs/create-system-account",
    "basics/cross-program-invocation/anchor/programs/*",
    "basics/hello-solana/anchor/programs/*",
    "basics/pda-rent-payer/anchor/programs/*",
    "basics/processing-instructions/anchor/programs/*",
    "basics/program-derived-addresses/anchor/programs/*",
    "basics/realloc/anchor/programs/*",
    "basics/rent/anchor/programs/*",
    "basics/repository-layout/anchor/programs/*",
    "basics/transfer-sol/anchor/programs/*",
]

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[features]
idl-build = ["anchor-lang/idl-build"]
