name: Anchor

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SOLANA_VERSION: 1.18.17
  ANCHOR_VERSION: 0.30.1

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            anchor:
              - '**/anchor/**'
          list-files: json

  build-and-test:
    needs: changes
    if: ${{ needs.changes.outputs.projects != '[]' && needs.changes.outputs.projects != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJson(needs.changes.outputs.projects) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup Anchor and Solana
        uses: heyAyushh/setup-anchor@v4.0
        with:
          anchor-version: ${{ env.ANCHOR_VERSION }}
          solana-cli-version: ${{ env.SOLANA_VERSION }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Build and Test Project
        run: |
          project=$(dirname "${{ matrix.project }}")
          echo "Processing $project"
          cd "$project"
          if ! anchor build; then
            echo "::error file=$project/Cargo.toml::Failed to build $project"
            echo "- :x: $project (Build Failed)" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
          if ! pnpm install --frozen-lockfile || ! anchor test; then
            echo "::error file=$project/Cargo.toml::Failed to test $project"
            echo "- :x: $project (Test Failed)" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
          echo "- :white_check_mark: $project" >> $GITHUB_STEP_SUMMARY

  summary:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Summary
        run: |
          echo "## Anchor Workflow Summary" >> $GITHUB_STEP_SUMMARY
          echo "Solana Version: ${{ env.SOLANA_VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "Anchor Version: ${{ env.ANCHOR_VERSION }}" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ needs.build-and-test.result }}" == "success" ]]; then
            echo ":white_check_mark: All projects completed successfully" >> $GITHUB_STEP_SUMMARY
          else
            echo ":x: Some projects encountered errors" >> $GITHUB_STEP_SUMMARY
          fi
          echo "Check individual job logs for details on errors and failures." >> $GITHUB_STEP_SUMMARY
