name: Anchor

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

env:
  MAX_JOBS: 4
  PROJECTS_PER_JOB: 4

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      should_build_and_test_all: ${{ steps.analyze.outputs.build_and_test_all }}
      changed_projects: ${{ steps.analyze.outputs.changed_projects }}
      total_projects: ${{ steps.analyze.outputs.total_projects }}
      matrix_indices: ${{ steps.matrix.outputs.matrix_indices }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        if: github.event_name == 'pull_request'
        with:
          list-files: shell
          filters: |
            anchor:
              - added|modified: '**/anchor/**'
            ignore:
              - added|modified: '.github/.ghaignore'
            workflow:
              - added|modified: '.github/workflows/anchor.yml'
      - name: Analyze Changes
        id: analyze
        run: |
          ignore_pattern=$(grep . .github/.ghaignore | grep -v '^$' | tr '\n' '|' | sed 's/|$//')
          echo "Ignore pattern: $ignore_pattern"

          function get_projects() {
            find . -type d -name "anchor" | grep -vE "$ignore_pattern" | sort
          }

          if [[ "${{ github.event_name }}" == "push" || "${{ github.event_name }}" == "schedule" || "${{ steps.changes.outputs.ignore }}" == "true" || "${{ steps.changes.outputs.workflow }}" == "true" ]]; then
            echo "build_and_test_all=true" >> $GITHUB_OUTPUT
            projects=$(get_projects)
          elif [[ "${{ steps.changes.outputs.anchor }}" == "true" ]]; then
            echo "build_and_test_all=false" >> $GITHUB_OUTPUT
            changed_files=(${{ steps.changes.outputs.anchor_files }})
            projects=$(for file in "${changed_files[@]}"; do dirname "${file}" | grep anchor | sed 's#/anchor/.*#/anchor#g'; done | grep -vE "$ignore_pattern" | sort -u)
          else
            echo "build_and_test_all=false" >> $GITHUB_OUTPUT
            projects=""
          fi

          if [[ -n "$projects" ]]; then
            echo "::group::Projects to build and test"
            echo "$projects"
            echo "::endgroup::"
            total_projects=$(echo "$projects" | wc -l)
            echo "Total projects: $total_projects"
            echo "total_projects=$total_projects" >> $GITHUB_OUTPUT
            echo "changed_projects=$(echo "$projects" | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
          else
            echo "No projects to build and test."
            echo "total_projects=0" >> $GITHUB_OUTPUT
            echo "changed_projects=[]" >> $GITHUB_OUTPUT
          fi
      - name: Generate matrix indices
        id: matrix
        run: |
          total_projects=${{ steps.analyze.outputs.total_projects }}
          projects_per_job=${{ env.PROJECTS_PER_JOB }}
          max_jobs=${{ env.MAX_JOBS }}

          num_jobs=$(( (total_projects + projects_per_job - 1) / projects_per_job ))
          num_jobs=$(( num_jobs > max_jobs ? max_jobs : num_jobs ))

          indices=$(seq 0 $(( num_jobs - 1 )) | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix_indices=$indices" >> $GITHUB_OUTPUT

  build-and-test:
    needs: changes
    if: needs.changes.outputs.total_projects != '0'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        index: ${{ fromJson(needs.changes.outputs.matrix_indices) }}
    steps:
      - uses: actions/checkout@v4
      - uses: heyAyushh/setup-anchor@v4.0
        with:
          anchor-version: 0.30.1
          solana-cli-version: 1.18.17
          node-version: 20.x
      - name: Display Versions and Install pnpm
        run: |
          solana -V
          solana-keygen new --no-bip39-passphrase
          rustc -V
          anchor -V
          npm i -g pnpm
      - name: Build and Test
        run: |
          function build_and_test() {
            local project=$1
            echo "Building and Testing $project"
            cd "$project"

            if ! anchor build; then
              echo "::error::anchor build failed for $project"
              echo "$project: anchor build failed" >> $GITHUB_WORKSPACE/failed_projects.txt
              return 1
            fi

            if ! pnpm install --frozen-lockfile; then
              echo "::error::pnpm install failed for $project"
              echo "$project: pnpm install failed" >> $GITHUB_WORKSPACE/failed_projects.txt
              return 1
            fi

            if ! anchor test; then
              echo "::error::anchor test failed for $project"
              echo "$project: anchor test failed" >> $GITHUB_WORKSPACE/failed_projects.txt
              return 1
            fi

            echo "Build and tests succeeded for $project."
            rm -rf target node_modules
            return 0
          }

          readarray -t all_projects < <(echo '${{ needs.changes.outputs.changed_projects }}' | jq -r '.[]?')
          start_index=$(( ${{ matrix.index }} * ${{ env.PROJECTS_PER_JOB }} ))
          end_index=$(( start_index + ${{ env.PROJECTS_PER_JOB }} ))

          echo "::group::Projects to build and test in this job"
          for i in $(seq $start_index $(( end_index - 1 ))); do
            if [[ $i -lt ${#all_projects[@]} ]]; then
              echo "${all_projects[$i]}"
            fi
          done
          echo "::endgroup::"

          failed=false
          for i in $(seq $start_index $(( end_index - 1 ))); do
            if [[ $i -lt ${#all_projects[@]} ]]; then
              echo "::group::Building and testing ${all_projects[$i]}"
              if ! build_and_test "${all_projects[$i]}"; then
                failed=true
              fi
              echo "::endgroup::"
            fi
          done

          if [[ "$failed" == "true" ]]; then
            echo "::group::Failed projects"
            cat $GITHUB_WORKSPACE/failed_projects.txt
            echo "::endgroup::"
            exit 1
          fi

  summary:
    needs: [changes, build-and-test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create job summary
        run: |
          echo "## Anchor Workflow Summary" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ needs.changes.outputs.should_build_and_test_all }}" == "true" ]]; then
            echo "- Built and tested all projects" >> $GITHUB_STEP_SUMMARY
          else
            echo "- Built and tested changed projects:" >> $GITHUB_STEP_SUMMARY
            echo '${{ needs.changes.outputs.changed_projects }}' | jq -r '.[]' | while read project; do
              echo "  - $project" >> $GITHUB_STEP_SUMMARY
            done
          fi

          if [[ "${{ needs.build-and-test.result }}" == "failure" ]]; then
            echo "## :x: Build or tests failed" >> $GITHUB_STEP_SUMMARY
            echo "### Failed projects:" >> $GITHUB_STEP_SUMMARY
            cat $GITHUB_WORKSPACE/failed_projects.txt >> $GITHUB_STEP_SUMMARY 2>/dev/null || echo "No failed projects file found." >> $GITHUB_STEP_SUMMARY
          elif [[ "${{ needs.build-and-test.result }}" == "success" ]]; then
            echo "## :white_check_mark: All builds and tests passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "## :warning: Build and test job was skipped or canceled" >> $GITHUB_STEP_SUMMARY
          fi
