name: Anchor Build and Test

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

env:
  ANCHOR_VERSION: "0.30.1"
  SOLANA_VERSION: "1.18.17"
  NODE_VERSION: "20.x"

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      anchor: ${{ steps.filter.outputs.anchor }}
      ghaignore: ${{ steps.filter.outputs.ghaignore }}
      anchor_yml: ${{ steps.filter.outputs.anchor_yml }}
      anchor_files: ${{ steps.filter.outputs.anchor_files }}
      should_run: ${{ steps.check.outputs.should_run }}
      project_batches: ${{ steps.process.outputs.project_batches }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: shell
          filters: |
            anchor:
              - added|modified: '**/anchor/**'
            ghaignore:
              - '.github/.ghaignore'
            anchor_yml:
              - '.github/workflows/anchor.yml'

      - name: Check if build should run
        id: check
        run: |
          if [[ "${{ github.event_name }}" == "schedule" || "${{ github.event_name }}" == "push" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            if [[ "${{ steps.filter.outputs.anchor }}" == "true" || \
                  "${{ steps.filter.outputs.ghaignore }}" == "true" || \
                  "${{ steps.filter.outputs.anchor_yml }}" == "true" ]]; then
              echo "should_run=true" >> $GITHUB_OUTPUT
            else
              echo "should_run=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

      - name: Process Anchor projects
        id: process
        if: steps.check.outputs.should_run == 'true'
        run: |
          set -e

          create_ignore_regex() {
            grep -v '^#' .github/.ghaignore 2>/dev/null | sed 's/^/^/' | sed 's/$/\//' | tr '\n' '|' | sed 's/|$//' || echo ""
          }

          filter_projects() {
            local ignore_regex="$1"
            if [[ -n "$ignore_regex" ]]; then
              grep -vE "$ignore_regex" || true
            else
              cat
            fi
          }

          batch_projects() {
            local batch_size=5
            jq -R -s 'split("\n")[:-1] | _nwise('"$batch_size"') | map(select(length > 0))' | jq -c '.'
          }

          ignore_regex=$(create_ignore_regex)

          if [[ "${{ github.event_name }}" == "pull_request" && \
                "${{ steps.filter.outputs.ghaignore }}" != "true" && \
                "${{ steps.filter.outputs.anchor_yml }}" != "true" ]]; then
            changed_files="${{ steps.filter.outputs.anchor_files }}"
            projects=$(echo "$changed_files" | grep '/anchor/' | sed 's/\/anchor\/.*$/\/anchor/' | sort -u)
          else
            projects=$(find . -type d -name "anchor")
          fi

          filtered_projects=$(echo "$projects" | filter_projects "$ignore_regex")

          if [[ -z "$filtered_projects" ]]; then
            echo "::notice::No projects to process after filtering."
            echo "project_batches=[]" >> $GITHUB_OUTPUT
          else
            batches=$(echo "$filtered_projects" | batch_projects)
            echo "project_batches=$batches" >> $GITHUB_OUTPUT
            echo "::notice::Projects to process: $filtered_projects"
          fi
        shell: bash

  build-and-test:
    needs: changes
    if: needs.changes.outputs.should_run == 'true' && fromJson(needs.changes.outputs.project_batches)[0]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        batch: ${{ fromJson(needs.changes.outputs.project_batches) }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Anchor
        uses: heyAyushh/setup-anchor@v4.0
        with:
          anchor-version: ${{ env.ANCHOR_VERSION }}
          solana-cli-version: ${{ env.SOLANA_VERSION }}
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Display versions
        run: |
          solana -V
          solana-keygen new --no-bip39-passphrase
          rustc -V
          anchor -V

      - name: Process Anchor projects
        run: |
          set -x
          for project in ${{ toJson(matrix.batch) }}; do
            echo "Processing project: $project"
            cd "$project" || continue

            echo "Building $project"
            if ! anchor build; then
              echo "::error file=${project}::Build failed for $project"
              exit 1
            fi

            echo "Installing dependencies for $project"
            if ! pnpm install --frozen-lockfile; then
              echo "::error file=${project}::Dependency installation failed for $project"
              exit 1
            fi

            echo "Running tests for $project"
            if ! anchor test; then
              echo "::error file=${project}::Tests failed for $project"
              exit 1
            fi

            echo "Build and tests succeeded for $project"
            cd - > /dev/null || exit
          done
        shell: bash

      - name: Generate job summary
        if: always()
        run: |
          {
            echo "## Batch Results (Solana ${{ env.SOLANA_VERSION }})"
            echo "Processed projects:"
            for project in ${{ toJson(matrix.batch) }}; do
              echo "- $project"
            done
            echo "Status: ${{ job.status }}"
          } >> $GITHUB_STEP_SUMMARY

  summary:
    needs: build-and-test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Summarize results
        run: |
          echo "# Anchor Build and Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ needs.build-and-test.result }}" == "success" ]]; then
            echo "✅ All projects built and tested successfully." >> $GITHUB_STEP_SUMMARY
          elif [[ "${{ needs.build-and-test.result }}" == "skipped" ]]; then
            echo "ℹ️ Build and test job was skipped." >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Some projects failed to build or test. Check the build logs for details." >> $GITHUB_STEP_SUMMARY
          fi
        shell: bash
